apiVersion: v1
kind: Service
metadata:
  name: iris-log-ml-service
spec:
  selector:
    app: iris-log-ml-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer
